# Coding Lab 2
## Pacakges, ndarrays, Plotting, and Numerical Integration
## Real Stellar Models
### AST4301, Prof. Faus
### **Due 2024 Feb 23, Start of Class**

In this coding lab, we will about higher-level data structures that are useful for scientific programming. We will also learn how to make plots and figures using Python.

We will use these coding tools to visualize real stellar models, and do some calculations with them.

**Full Effort:** To receive a check, you need to demonstrate full effort. You should run your code in every cell (`Shift+Enter`). If the code raises an error, you should try to debug it. 

If you try to debug things for 2 or 3 hours but can't get it to work, make a note of where you stopped with a comment or print function in the cell. Explain in one or two sentences what the error or problem that you are seeing is and what confusion(s) it is causing you.

If you don't give an explanation of why there are errors in your code cells or why you did not complete the notebook, you will receive a check-minus.

A check-plus is worth extra credit---one check-plus balances a check-minus. So a check-plus gives you 1.5 percentage points on your final grade. If you want to aim for extra-credit, you have until Friday (Feb. 23) at 10am to work on the coding lab. It is worth saying that I will help you with the coding lab if you bring it to office hours or make an appointment.

### 1. Packages

A Package is some set of useful code or software tools that someone has devleoped and made available. In python, there are a lot of freely-available packages. You can find a large list of Packages on the Python Package Index, aka PyPI: https://pypi.org/. 

A Package is sometimes also called a "module" or a "library." Especially in other languages (like C), libraries are a common term.  In some cases, there are technical meanings; for example, a python package is usually made up of one or more modules. But the basic idea for all of these terms (package, module, or library) is that these are extensions to the core language that give you more functionality.

Two very important packages for scientific computing in python are `numpy` and `matplotlib`. `numpy` is short for Numeric Python. `matplotlib` is a package that will plot data for you.

Both packages are very large, in terms of the number of tools and functions that are avaialbe. The packages also have a large userbase and developer base, and you can find a lot of documentation and help for using these pacakges. You should know about the websites, in case you need to find help or read the manuals:

https://numpy.org/

https://matplotlib.org/

It is worth saying that there are other packages out there that do similar things, if not the same things, as these two. But `numpy` and `matplotlib` are probably the most standard and well-known packages.

A great thing about python is that it is very easy to use packages. To access the tools, you use an `import` command, like this:


In [1]:
import numpy
import matplotlib

This gives you access to all of the tools in numpy or matplotlib. You access them with a `.`, for example

In [5]:
x = [1,2,3]
y = [2,4,8]
dot_product = numpy.dot(x,y)
print(dot_product)

34


So, this function called `numpy.dot` calculated the dot product for 2 lists, x and y.  This function is part of the `numpy` package; in general, you need to know about/learn functions in numpy to make the best use of it.

We will do some practice with `matplotlib` a bit further down.

It is tedious to keep typing `numpy` or `matplotlib`. You can rename any package when you import it in python. In principle, you can name things whatever you want. In practice, people usually change `numpy` to `np`, with the following command:

In [74]:
import numpy as np

x = [1,2,3]
y = [2,4,8]
dot_product = np.dot(x,y)
print(dot_product)

34


The best thing to do is to import all of your tools at the very start of your program or notebook---we have already taken care of that.

### 2. Data Structures and the ndarray

Most packages give you new data structures. We already encountered one kind of data structure, the list.  Remember, for example, that we can add objects to a list in the following way:

In [76]:
sample_list = [1,2.2, 3.3]
print('print statement 1:',sample_list)

for ii in range(5):
    sample_list.append(4.4 + ii*1.1)
print('print 2, after appending elements',sample_list)

print statement 1: [1, 2.2, 3.3]
print 2, after appending elements [1, 2.2, 3.3, 4.4, 5.5, 6.6000000000000005, 7.700000000000001, 8.8]


A list can do other things as well:

In [77]:
#add an element to the middle of a list

#first argument of `insert` is the index number, second element is the thing you want to insert
sample_list.insert(2, 9.9)

#here, you will see that `9.9` has been put in the 3rd place in the list
print('Contents of sample list after inserting 9.9 in the 3rd index:')
print(sample_list)

#sort the list
#there is a function called sort, you call it with no arguments and it will sort your data structure
sample_list.sort()
print('Contents of sample list after sorting:')
print(sample_list)

Contents of sample list after inserting 9.9 in the 3rd index:
[1, 2.2, 9.9, 3.3, 4.4, 5.5, 6.6000000000000005, 7.700000000000001, 8.8]
Contents of sample list after sorting:
[1, 2.2, 3.3, 4.4, 5.5, 6.6000000000000005, 7.700000000000001, 8.8, 9.9]


In some ways, what makes a list a data structure is that (a) it serves as a container for the data, and (b) gives you functions to do things with the data.

Two short-comings of lists are (1) math and function operations are hard, because you have to look up the elements of the list with the index; so usually you do operations on lists in a loop. (2) Looping over a list in python is not very efficient; it can be slow to do a loop over millions of elements in a list.

In [79]:
#If I want to add 100 to every element in the list, I have to do this:
for ii in range(len(sample_list)):
    sample_list[ii] = sample_list[ii] + 100
print(sample_list)


#but this code will cause a TypeError
sample_list + 100


[201, 202.2, 203.3, 204.4, 205.5, 206.6, 207.7, 208.8, 209.9]


TypeError: can only concatenate list (not "int") to list

However, `numpy` has a special data structure called the `ndarray`, which fixes both of these problems. `ndarrays` make math very easy for a collection of data elements. `ndarray` objects are also super efficient, and can do lots of operations across the array quickly. (Under the hood, a lot of `numpy` is written in C, which runs very quickly on loops.)

In [80]:
#We can build an ndarray in different ways. For example, we can convert a list to an ndarray
print(type(sample_list))
sample_list = np.array(sample_list)
print(type(sample_list))
print(sample_list)
print(sample_list + 100)

<class 'list'>
<class 'numpy.ndarray'>
[201.  202.2 203.3 204.4 205.5 206.6 207.7 208.8 209.9]
[301.  302.2 303.3 304.4 305.5 306.6 307.7 308.8 309.9]


`ndarrays` get even better. If you want to do operations on ndarrays of the same size, `numpy` matches elements, one at a time.  This is called "vectorization." It makes our code much easier ot read, because we don't need to loop over the data structs. We can also assign a variable name to an ndarray and use it in an equation.

In [84]:
#in the last coding lab, we caulculated the area of an ellipse like this.
major_axis = [1.1, 2.2, 3.3, 4.4 ]
minor_axis = [0.1, 0.2, 0.3, 0.4 ]
#BTW, numpy has some built in constants, like pi
#so we don't need to define it for ourselves
#pi = 3.14159
print(np.pi)

for ii in range(len( major_axis)):
    major_axis_use = major_axis[ii]
    minor_axis_use = minor_axis[ii]
    area_of_ellipse = np.pi*major_axis_use*minor_axis_use
    
    print('area of ellipse ', ii,':  ', area_of_ellipse)


#Notice how much easier it is to read with ndarrays. 
major_axis = np.array([1.1, 2.2, 3.3, 4.4 ])
minor_axis = np.array([0.1, 0.2, 0.3, 0.4 ])
areas = np.pi*major_axis*minor_axis
print(areas)

#The ndarrays also do the arithmetic faster than the lists. 
#We might notice this if we tried to do a lists with a million elements or so

3.141592653589793
area of ellipse  0 :   0.3455751918948773
area of ellipse  1 :   1.3823007675795091
area of ellipse  2 :   3.110176727053895
area of ellipse  3 :   5.529203070318037
[0.34557519 1.38230077 3.11017673 5.52920307]


By default, you should usually plan to use ndarrays in `numpy`. When doing data science with python or scientific computing, ndarrays are one of the best options. (I would argue they are the best overall, but that is an opinion.)

Here are some other important and useful numpy functions.  See also the `numpy` tutorial for beginners (https://numpy.org/doc/stable/user/absolute_beginners.html) and `numpy` fundamentals (https://numpy.org/doc/stable/user/basics.html).

In [86]:
#ways to make an ndarray:

#make a new array. The two arguments set the begining and end
new_array1 = np.arange(1,11)
print('new_array1:',new_array1)

#the third argument sents the spacing
new_array2 = np.arange(1,11, 0.2)
print('new_array2:',new_array2)

#if you don't know the spacing but know the number of elements that you want
#in this case, we make it with 30 elements, evenly spaced
new_array3 = np.linspace(1,11,30)
print('lenght of new_array3:',len(new_array3))
print('new_array3:',new_array3)


#make a new array that is all ones or zeros
#the argument gives the size of the array you need)
array_of_zeros = np.zeros(10)
print('array_of_zeros:',array_of_zeros)

array_of_ones = np.ones(15)
print('array_of_ones',array_of_ones)



new_array1: [ 1  2  3  4  5  6  7  8  9 10]
new_array2: [ 1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6
  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6  5.8  6.   6.2  6.4
  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2
  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8]
lenght of new_array3: 30
new_array3: [ 1.          1.34482759  1.68965517  2.03448276  2.37931034  2.72413793
  3.06896552  3.4137931   3.75862069  4.10344828  4.44827586  4.79310345
  5.13793103  5.48275862  5.82758621  6.17241379  6.51724138  6.86206897
  7.20689655  7.55172414  7.89655172  8.24137931  8.5862069   8.93103448
  9.27586207  9.62068966  9.96551724 10.31034483 10.65517241 11.        ]
array_of_zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array_of_ones [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [87]:
#the `nd` part of `ndarray` is N-Dimensions. Here is a 1-D, 2-D, 3-D, and 4-D array
x1d = np.arange(0,3)
print('The shape of x1d is:',np.shape(x1d))
print(x1d)
x2d = np.arange(0,9).reshape(3,3)
print('The shape of x2d is:',np.shape(x2d))
print(x2d)
x3d = np.arange(0,27).reshape(3,3,3)
print('The shape of x3d is:',np.shape(x3d))
print(x3d)
x4d = np.arange(0,81).reshape(3,3,3,3)
print('The shape of x4d is:',np.shape(x4d))
print(x4d)

The shape of x1d is: (3,)
[0 1 2]
The shape of x2d is: (3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
The shape of x3d is: (3, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
The shape of x4d is: (3, 3, 3, 3)
[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]


 [[[54 55 56]
   [57 58 59]
   [60 61 62]]

  [[63 64 65]
   [66 67 68]
   [69 70 71]]

  [[72 73 74]
   [75 76 77]
   [78 79 80]]]]


In [88]:
#numpy functions to act on ndarrays
x = np.arange(1,11)
print('log_10 of x', np.log10(x))
print('log of x',    np.log(x))
print('sqrt(x)',     np.sqrt(x))
print('x^2', np.power(x,2))
print('e^x', np.exp(x))

log_10 of x [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]
log of x [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
sqrt(x) [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
x^2 [  1   4   9  16  25  36  49  64  81 100]
e^x [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
